[package]
name = "simpledns"
authors = ["Luna Cybi"]
version = "0.1.0"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.17"
rand = "0.8.5"
yaml-rust = "0.4"
clap = { version = "3.2.16", features = ["derive"] }
