[package]
name = "thread-pooler"
version = "0.1.0"
edition = "2021"

[lib]
name = "thread_pooler"
path = "src/lib.rs"

[dependencies]
rand = "0.8.5"
uuid = { version = "1.11.0", "features" = [ "v4", "fast-rng" ] }
